### PR TITLE
Fix ofv profiles calculation and grid search

### LINKED ISSUE #92: gridSearch() fails in the vignette example
Same as here https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/issues/91

### PR DESCRIPTION
**Pull request by rengelke**
Closes #92

### CODE REVIEW

File: R/ParameterIdentification.R [hunk 1]
```diff
@@ -651,165 +651,175 @@ ParameterIdentification <- R6::R6Class(
...
+      # Set parameter values and bounds
+      if (is.null(par) || length(par) != nrOfParameters || !is.numeric(par)) {
+        par <- sapply(private$.piParameters, function(x) x$currValue)
+      }
+      lower <- lower %||% 0.9 * par
+      upper <- upper %||% 1.1 * par
+
+      # Calculate grid size
+      gridSize <- if (is.null(totalEvaluations)) {
+        21
```
Comment (PavelBal) [inline R/ParameterIdentification.R:776]: No magic numbers in the code!

**Review by PavelBal — CHANGES_REQUESTED** [review]
I did not check the code properly, I hope it works ;)

File: R/ParameterIdentification.R (hunk 1 above)
Comment (rengelke) [reply R/ParameterIdentification.R:776]: The number was there - so I thought there is a rationale behind it. Seems not

**Review by PavelBal — APPROVED** [review]

**Comment by rengelke** [comment]
> I did not check the code properly, I hope it works ;)

Works like a charm - tests cover most scenarios.

Need your feedback here: Fall back to linear scaling when `logScaleFlag = TRUE` and lower/upper bounds are negative. It makes more sense to me.

```
for (idx in seq_along(private$.piParameters)) {
        if (logScaleFlag[idx] && lower[idx] > 0 && upper[idx] > 0) {
          # Logarithmic scaling
          parameterGrid[[idx]] <- exp(seq(
            log(lower[idx]),
            log(upper[idx]),
            length.out = gridSize
          ))
        } else {
          if (logScaleFlag[idx]) {
            # Warning when falling back to linear scaling
            message(messages$logScaleFallbackWarning(
              private$.piParameters[[idx]]$parameters[[1]]$path
            ))
          }
          # Linear scaling
          parameterGrid[[idx]] <- seq(lower[idx], upper[idx], length.out = gridSize)
        }
      }
```

File: R/ParameterIdentification.R [hunk 2]
```diff
@@ -651,165 +651,175 @@ ParameterIdentification <- R6::R6Class(
...
+    #' Generates OFV profiles by varying each parameter independently while
+    #' holding others constant.
+    #'
+    #' @param par Numeric vector of parameter values, one for each parameter.
+    #' Defaults to current parameter values if `NULL`, invalid or mismatched.
+    #' @param lower Numeric vector of lower bounds for parameters. Defaults to
+    #' 0.9 * `par`.
+    #' @param upper Numeric vector of upper bounds for parameters. Defaults to
+    #' 1.1 * `par`.
+    #' @param totalEvaluations Integer specifying the total number of grid
```
[the remark this answers is not in the document]
Comment (rengelke) [reply R/ParameterIdentification.R:763]: Replaced `upper` / `lower` by parameter `boundFactor`.

```
#' @param boundFactor Numeric value. A value of 0.1 means `lower` is 10% below  `par` and `upper` is 10% above `par`. Default is `0.1`.
```

File: R/ParameterIdentification.R (hunk 1 above)
Comment (rengelke) [reply R/ParameterIdentification.R]: Default `totalEvaluations = 20` controls directly grid size for all parameters

**Comment by PavelBal** [comment]
> Need your feedback here: Fall back to linear scaling when logScaleFlag = TRUE and lower/upper bounds are negative. It makes more sense to me.

I prefer to stop and throw an error. Clearly, the user tries to do something that does not make sense.
